module.exports =
  {
    purge:
      [
        './src/**/*.html',
        './src/**/*.vue',
        './src/**/*.jsx',
        './src/**/*.tsx'
      ],
    darkMode: false, // or 'media' or 'class'
    theme:
      {
        extend:
          {
            colors:
              {
                primary:
                  '#3490dc',
                secondary:
                  '#ffed4a',
                accent:
                  '#e3342f',
                background:
                  '#ffffff'
              }
          }
      },
    variants:
      {
        extend:
          {}
      },
    plugins:
      []
  }
